name: Deploy to GCP
on:
  push:
    branches:
      - test

permissions:
  id-token: write
  content: read

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - id: "auth"
        name: "Authenticate to GCP"
        uses: "google-github-actions/auth@v0.3.1"
        with:
          create_credentials_file: "true"
          workload_identity_provider: "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.GCP_SERVICE_ACCOUNT }}"

      - id: "gcloud"
        name: "gcloud"
        run: |
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud services list
